Repository d-zone-org/d-zone, pull requests merged in 2020-12, with the labels that each got.

#252 Replace ECSY with Ape ECS
  .babelrc
  .gitignore
  .prettierignore
  interfaces/websocket.ts
  next.config.js
  nodemon.json
  package.json
  server/components/discord-client.ts
  server/components/next-wrapper.ts
  server/components/websocket.ts
  server/index.ts
  server/utils/config.ts
  src/art/banner.png
  src/art/banner.xcf
  src/art/sprite-config.json
  src/art/sprites-light.aseprite
  src/components/complex/game/common/actor-cell.ts
  src/components/complex/game/engine/benchmark.ts
  src/components/complex/game/engine/components/actor.ts
  src/components/complex/game/engine/components/hop.ts
  src/components/complex/game/engine/components/map-cell.ts
  src/components/complex/game/engine/components/pixi-sprite.ts
  src/components/complex/game/engine/components/render.ts
  src/components/complex/game/engine/components/sprite.ts
  src/components/complex/game/engine/components/transform.ts
  src/components/complex/game/engine/engine.ts
  src/components/complex/game/engine/systems/hop.ts
  src/components/complex/game/engine/systems/map.ts
  src/components/complex/game/engine/systems/sprite.ts
  src/components/complex/game/engine/systems/transform.ts
  src/components/complex/game/game.ts
  src/components/complex/game/index.tsx
  src/components/complex/game/renderer/renderer.ts
  src/components/complex/game/renderer/resources/loader.ts
  src/components/complex/game/renderer/resources/resources.ts
  src/components/complex/game/renderer/wheel-stepped.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/typings/pixi-cull.d.ts
  yarn.lock
Labels: dependencies, 🦋 rewrite

#257 ESLint integration
  .eslintrc.json
  .vscode/extensions.json
  .vscode/settings.json
  .yarn/sdks/integrations.yml
  .yarn/sdks/prettier/index.js
  .yarn/sdks/prettier/package.json
  .yarn/sdks/typescript/bin/tsc
  .yarn/sdks/typescript/bin/tsserver
  .yarn/sdks/typescript/lib/tsc.js
  .yarn/sdks/typescript/lib/tsserver.js
  .yarn/sdks/typescript/lib/typescript.js
  .yarn/sdks/typescript/package.json
  .yarnrc.yml
  package.json
  packages/pixi-viewport/@types/viewport.es.d.ts
  packages/pixi-viewport/LICENSE
  packages/pixi-viewport/README.md
  packages/pixi-viewport/package.json
  packages/pixi-viewport/src/viewport.es.js
  packages/pixi-viewport/tsconfig.json
  server/components/next-wrapper.ts
  src/components/complex/game/common/actor-cell.ts
  src/components/complex/game/common/map.ts
  src/components/complex/game/common/projection.ts
  src/components/complex/game/engine/benchmark.ts
  src/components/complex/game/engine/components/render.ts
  src/components/complex/game/engine/systems/hop.ts
  src/components/complex/game/engine/systems/map.ts
  src/components/complex/game/engine/systems/sprite.ts
  src/components/complex/game/engine/systems/transform.ts
  src/components/complex/game/game.ts
  src/components/complex/game/renderer/renderer.ts
  src/components/complex/game/renderer/resources/loader.ts
  src/components/complex/game/renderer/resources/resources.ts
  src/components/complex/game/renderer/wheel-stepped.ts
  src/components/complex/game/typings.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/typings/pixi-cull.d.ts
  tsconfig.json
  yarn.lock
Labels: ⚙️ core, ⚡ enhancement, 🦋 rewrite

#261 Improve map system 🗺
  src/modules/game/common/cell-3d.ts
  src/modules/game/common/map-3d.ts
  src/modules/game/constants.ts
  src/modules/game/engine/archetypes/actor.ts
  src/modules/game/engine/seed-dev.ts
  src/modules/game/engine/systems/hop.ts
  src/modules/game/index.ts
Labels: ⚡ enhancement, 🦋 rewrite

#263 Add documentation 📝
  .eslintrc.json
  .github/workflows/docs.yml
  .gitignore
  .prettierignore
  .yarn/releases/yarn-sources.cjs
  package.json
  packages/pixi-cull/@types/simple.d.ts
  packages/pixi-cull/@types/spatial-hash.d.ts
  packages/pixi-cull/code/simple.js
  packages/pixi-cull/code/spatial-hash.js
  packages/pixi-viewport/@types/viewport.es.d.ts
  packages/pixi-viewport/src/viewport.es.js
  src/modules/game/common/cell-3d.ts
  src/modules/game/common/map-3d.ts
  src/modules/game/common/projection.ts
  src/modules/game/config/sprite.ts
  src/modules/game/engine/archetypes/actor.ts
  src/modules/game/engine/components/actor.ts
  src/modules/game/engine/components/hop.ts
  src/modules/game/engine/components/map-cell.ts
  src/modules/game/engine/components/pixi-sprite.ts
  src/modules/game/engine/components/sprite.ts
  src/modules/game/engine/components/transform.ts
  src/modules/game/engine/index.ts
  src/modules/game/engine/register-ecs.ts
  src/modules/game/engine/seed-dev.ts
  src/modules/game/engine/systems/hop.ts
  src/modules/game/engine/systems/map.ts
  src/modules/game/engine/systems/sprite.ts
  src/modules/game/engine/systems/transform.ts
  src/modules/game/renderer/index.ts
  src/modules/game/renderer/resources/loader.ts
  src/modules/game/renderer/resources/resources.ts
  tsconfig.json
  yarn.lock
Labels: ✍️ docs, 🦋 rewrite

#265 Overhaul map system 🗺
  package.json
  src/modules/game/common/cell-3d.ts
  src/modules/game/common/map-3d.ts
  src/modules/game/common/projection.ts
  src/modules/game/engine/archetypes/actor.ts
  src/modules/game/engine/components/hop.ts
  src/modules/game/engine/components/map-cell.ts
  src/modules/game/engine/components/map.ts
  src/modules/game/engine/components/transform.ts
  src/modules/game/engine/index.ts
  src/modules/game/engine/register-ecs.ts
  src/modules/game/engine/seed-dev.ts
  src/modules/game/engine/systems/hop.ts
  src/modules/game/engine/systems/map.ts
  src/modules/game/index.ts
  yarn.lock
Labels: ⚡ enhancement, 🦋 rewrite

#267 Animation system 🏃‍♀️
  packages/pixi-viewport/@types/viewport.es.d.ts
  packages/pixi-viewport/src/viewport.es.js
  src/modules/game/common/map-3d.ts
  src/modules/game/common/projection.ts
  src/modules/game/config/sprite.ts
  src/modules/game/engine/archetypes/actor.ts
  src/modules/game/engine/components/animation.ts
  src/modules/game/engine/components/draw.ts
  src/modules/game/engine/components/graphic.ts
  src/modules/game/engine/components/hop.ts
  src/modules/game/engine/components/pixi-object.ts
  src/modules/game/engine/components/pixi-sprite.ts
  src/modules/game/engine/components/sprite.ts
  src/modules/game/engine/components/texture.ts
  src/modules/game/engine/register-ecs.ts
  src/modules/game/engine/seed-dev.ts
  src/modules/game/engine/systems/animation.ts
  src/modules/game/engine/systems/hop.ts
  src/modules/game/engine/systems/pixi.ts
  src/modules/game/engine/systems/sprite.ts
  src/modules/game/engine/systems/transform.ts
  src/modules/game/index.ts
  src/modules/game/renderer/index.ts
  src/modules/game/resources/animations.ts
  src/modules/game/resources/index.ts
  src/modules/game/resources/loader.ts
  src/modules/game/typings.ts
Labels: ⚙️ core, ⚡ enhancement, 🦋 rewrite
